# Generated by Django 2.0.9 on 2018-12-23 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellidos', models.CharField(max_length=70)),
                ('Edad', models.IntegerField()),
                ('Telefono', models.CharField(max_length=70)),
                ('email', models.EmailField(max_length=254)),
                ('Domicilio', models.TextField()),
            ],
        ),
    ]
